#[derive(Debug, Clone, Copy, PartialEq)]
pub enum Condition {
    TotalDictations(u64),
    TotalWords(u64),
    CurrentStreak(u64),
    DistinctActiveDays(u64),
    TotalActiveDays(u64),
    LearnedCorrections(u64),
    ManualDictionaryWords(u64),
    SnippetCount(u64),
    AppContextRules(u64),
    OnboardingDone,
    DictationInApp(&'static [&'static str]),
    DictationHourRange(u8, u8),
    DictationWordCountMin(u64),
    DictationWordCountExact(u64),
    DictationTotalMsMax(u64),
    DictationWpmMin(f64),
    AverageWpmMin(f64),
    TimeSavedMinutes(u64),
    DictationsInSameApp(u64),
    DistinctApps(u64),
    TextContains(&'static str),
    WeekendDictation,
    AudioDurationMsMin(u64),
    InjectFallbackUsed,
    ConsecutiveCancels(u32),
    PolyglotSameDay,
    LlmSkippedDictation,
    DictationsToday(u64),
    WordsToday(u64),
}
