use super::conditions::Condition;
use super::types::{AchievementCategory, AchievementTier};

#[derive(Debug, Clone, Copy)]
pub struct AchievementDef {
    pub id: &'static str,
    pub tier: AchievementTier,
    pub category: AchievementCategory,
    pub secret: bool,
    pub condition: Condition,
}

pub const ALL_ACHIEVEMENTS: &[AchievementDef] = &[
    // Milestones
    AchievementDef {
        id: "first_breath",
        tier: AchievementTier::Common,
        category: AchievementCategory::Milestones,
        secret: false,
        condition: Condition::TotalDictations(1),
    },
    AchievementDef {
        id: "getting_warm",
        tier: AchievementTier::Common,
        category: AchievementCategory::Milestones,
        secret: false,
        condition: Condition::TotalDictations(5),
    },
    AchievementDef {
        id: "regular",
        tier: AchievementTier::Common,
        category: AchievementCategory::Milestones,
        secret: false,
        condition: Condition::TotalDictations(50),
    },
    AchievementDef {
        id: "century_club",
        tier: AchievementTier::Rare,
        category: AchievementCategory::Milestones,
        secret: false,
        condition: Condition::TotalDictations(100),
    },
    AchievementDef {
        id: "dictation_machine",
        tier: AchievementTier::Rare,
        category: AchievementCategory::Milestones,
        secret: false,
        condition: Condition::TotalDictations(500),
    },
    AchievementDef {
        id: "ghost_writer",
        tier: AchievementTier::Legendary,
        category: AchievementCategory::Milestones,
        secret: false,
        condition: Condition::TotalDictations(1000),
    },
    AchievementDef {
        id: "word_nibbler",
        tier: AchievementTier::Common,
        category: AchievementCategory::Milestones,
        secret: false,
        condition: Condition::TotalWords(100),
    },
    AchievementDef {
        id: "word_feast",
        tier: AchievementTier::Common,
        category: AchievementCategory::Milestones,
        secret: false,
        condition: Condition::TotalWords(1000),
    },
    AchievementDef {
        id: "word_tsunami",
        tier: AchievementTier::Rare,
        category: AchievementCategory::Milestones,
        secret: false,
        condition: Condition::TotalWords(10000),
    },
    AchievementDef {
        id: "word_legend",
        tier: AchievementTier::Legendary,
        category: AchievementCategory::Milestones,
        secret: false,
        condition: Condition::TotalWords(100000),
    },
    // Streaks
    AchievementDef {
        id: "streak_3",
        tier: AchievementTier::Common,
        category: AchievementCategory::Streaks,
        secret: false,
        condition: Condition::CurrentStreak(3),
    },
    AchievementDef {
        id: "streak_7",
        tier: AchievementTier::Common,
        category: AchievementCategory::Streaks,
        secret: false,
        condition: Condition::CurrentStreak(7),
    },
    AchievementDef {
        id: "streak_14",
        tier: AchievementTier::Rare,
        category: AchievementCategory::Streaks,
        secret: false,
        condition: Condition::CurrentStreak(14),
    },
    AchievementDef {
        id: "streak_30",
        tier: AchievementTier::Legendary,
        category: AchievementCategory::Streaks,
        secret: false,
        condition: Condition::CurrentStreak(30),
    },
    // Speed
    AchievementDef {
        id: "faster_than_fingers",
        tier: AchievementTier::Rare,
        category: AchievementCategory::Speed,
        secret: false,
        condition: Condition::DictationWpmMin(80.0),
    },
    AchievementDef {
        id: "lightning_round",
        tier: AchievementTier::Rare,
        category: AchievementCategory::Speed,
        secret: false,
        condition: Condition::DictationTotalMsMax(800),
    },
    AchievementDef {
        id: "sonic_boom",
        tier: AchievementTier::Legendary,
        category: AchievementCategory::Speed,
        secret: false,
        condition: Condition::DictationWpmMin(120.0),
    },
    AchievementDef {
        id: "speed_saver",
        tier: AchievementTier::Rare,
        category: AchievementCategory::Speed,
        secret: false,
        condition: Condition::TimeSavedMinutes(60),
    },
    // Explorer
    AchievementDef {
        id: "dev_mode",
        tier: AchievementTier::Common,
        category: AchievementCategory::Explorer,
        secret: false,
        condition: Condition::DictationInApp(&["Code.exe", "Cursor.exe", "devenv.exe"]),
    },
    AchievementDef {
        id: "slack_attack",
        tier: AchievementTier::Common,
        category: AchievementCategory::Explorer,
        secret: false,
        condition: Condition::DictationInApp(&["slack.exe"]),
    },
    AchievementDef {
        id: "browser_bard",
        tier: AchievementTier::Common,
        category: AchievementCategory::Explorer,
        secret: false,
        condition: Condition::DictationInApp(&["chrome.exe", "firefox.exe", "msedge.exe"]),
    },
    AchievementDef {
        id: "first_snippet",
        tier: AchievementTier::Common,
        category: AchievementCategory::Explorer,
        secret: false,
        condition: Condition::SnippetCount(1),
    },
    AchievementDef {
        id: "snippet_collector",
        tier: AchievementTier::Rare,
        category: AchievementCategory::Explorer,
        secret: false,
        condition: Condition::SnippetCount(10),
    },
    AchievementDef {
        id: "stylist",
        tier: AchievementTier::Common,
        category: AchievementCategory::Explorer,
        secret: false,
        condition: Condition::AppContextRules(1),
    },
    AchievementDef {
        id: "graduate",
        tier: AchievementTier::Common,
        category: AchievementCategory::Explorer,
        secret: false,
        condition: Condition::OnboardingDone,
    },
    AchievementDef {
        id: "word_hoarder",
        tier: AchievementTier::Common,
        category: AchievementCategory::Explorer,
        secret: false,
        condition: Condition::ManualDictionaryWords(1),
    },
    AchievementDef {
        id: "explorer_apps",
        tier: AchievementTier::Rare,
        category: AchievementCategory::Explorer,
        secret: false,
        condition: Condition::DistinctApps(5),
    },
    // Learner
    AchievementDef {
        id: "autocorrect",
        tier: AchievementTier::Common,
        category: AchievementCategory::Learner,
        secret: false,
        condition: Condition::LearnedCorrections(1),
    },
    AchievementDef {
        id: "learned_ten",
        tier: AchievementTier::Common,
        category: AchievementCategory::Learner,
        secret: false,
        condition: Condition::LearnedCorrections(10),
    },
    AchievementDef {
        id: "learned_fifty",
        tier: AchievementTier::Rare,
        category: AchievementCategory::Learner,
        secret: false,
        condition: Condition::LearnedCorrections(50),
    },
    AchievementDef {
        id: "professor",
        tier: AchievementTier::Rare,
        category: AchievementCategory::Learner,
        secret: false,
        condition: Condition::ManualDictionaryWords(20),
    },
    // Extra visible
    AchievementDef {
        id: "time_saved_10",
        tier: AchievementTier::Common,
        category: AchievementCategory::Milestones,
        secret: false,
        condition: Condition::TimeSavedMinutes(10),
    },
    AchievementDef {
        id: "active_week",
        tier: AchievementTier::Common,
        category: AchievementCategory::Streaks,
        secret: false,
        condition: Condition::DistinctActiveDays(7),
    },
    AchievementDef {
        id: "wpm_sixty",
        tier: AchievementTier::Rare,
        category: AchievementCategory::Speed,
        secret: false,
        condition: Condition::AverageWpmMin(60.0),
    },
    AchievementDef {
        id: "first_week",
        tier: AchievementTier::Common,
        category: AchievementCategory::Streaks,
        secret: false,
        condition: Condition::TotalActiveDays(7),
    },
    // Secrets
    AchievementDef {
        id: "night_owl",
        tier: AchievementTier::Common,
        category: AchievementCategory::Secrets,
        secret: true,
        condition: Condition::DictationHourRange(0, 5),
    },
    AchievementDef {
        id: "early_bird",
        tier: AchievementTier::Common,
        category: AchievementCategory::Secrets,
        secret: true,
        condition: Condition::DictationHourRange(5, 7),
    },
    AchievementDef {
        id: "meta_calliop",
        tier: AchievementTier::Rare,
        category: AchievementCategory::Secrets,
        secret: true,
        condition: Condition::TextContains("calliop"),
    },
    AchievementDef {
        id: "triple_no",
        tier: AchievementTier::Common,
        category: AchievementCategory::Secrets,
        secret: true,
        condition: Condition::ConsecutiveCancels(3),
    },
    AchievementDef {
        id: "polyglot_day",
        tier: AchievementTier::Rare,
        category: AchievementCategory::Secrets,
        secret: true,
        condition: Condition::PolyglotSameDay,
    },
    AchievementDef {
        id: "brick_layer",
        tier: AchievementTier::Legendary,
        category: AchievementCategory::Secrets,
        secret: true,
        condition: Condition::DictationWordCountMin(500),
    },
    AchievementDef {
        id: "plan_b",
        tier: AchievementTier::Common,
        category: AchievementCategory::Secrets,
        secret: true,
        condition: Condition::InjectFallbackUsed,
    },
    AchievementDef {
        id: "weekend_warrior",
        tier: AchievementTier::Common,
        category: AchievementCategory::Secrets,
        secret: true,
        condition: Condition::WeekendDictation,
    },
    AchievementDef {
        id: "same_spot",
        tier: AchievementTier::Rare,
        category: AchievementCategory::Secrets,
        secret: true,
        condition: Condition::DictationsInSameApp(50),
    },
    AchievementDef {
        id: "long_winded",
        tier: AchievementTier::Rare,
        category: AchievementCategory::Secrets,
        secret: true,
        condition: Condition::AudioDurationMsMin(120_000),
    },
    AchievementDef {
        id: "raw_mode",
        tier: AchievementTier::Common,
        category: AchievementCategory::Secrets,
        secret: true,
        condition: Condition::LlmSkippedDictation,
    },
    AchievementDef {
        id: "night_shift",
        tier: AchievementTier::Common,
        category: AchievementCategory::Secrets,
        secret: true,
        condition: Condition::DictationHourRange(22, 24),
    },
    AchievementDef {
        id: "three_word_poem",
        tier: AchievementTier::Common,
        category: AchievementCategory::Secrets,
        secret: true,
        condition: Condition::DictationWordCountExact(3),
    },
    AchievementDef {
        id: "essay_mode",
        tier: AchievementTier::Rare,
        category: AchievementCategory::Secrets,
        secret: true,
        condition: Condition::DictationWordCountMin(200),
    },
    AchievementDef {
        id: "power_day",
        tier: AchievementTier::Legendary,
        category: AchievementCategory::Secrets,
        secret: true,
        condition: Condition::DictationsToday(20),
    },
];

pub fn achievement_by_id(id: &str) -> Option<&'static AchievementDef> {
    ALL_ACHIEVEMENTS.iter().find(|def| def.id == id)
}
